version: "2"

services:
  php:
    image: richarvey/nginx-php-fpm:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    links:
      - db
  db:
    image: mysql:5.6
    command: --innodb_use_native_aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
        - "9000:80"
     links:
       - "db:db"
